
###
GET http://localhost:5173/book

###
GET http://localhost:5173/book/2

###
POST http://localhost:5173/book
Content-Type: application/json

{
  "title": "Book 1",
  "author": 1
}

###
PUT http://localhost:5173/book/1
Content-Type: application/json

{
  "title": "The Great Gatsby Updated",
  "author": "F. Scott Fitzgerald"
}

###
DELETE http://localhost:5173/book/2